-- H2 2.3.232;
;             
CREATE USER IF NOT EXISTS "SA" SALT '9b03c4cc465de934' HASH 'e761d64cb234d0bb534cfb92038e2eaad5e3b0948869a63fc40da3ede6f22ead' ADMIN;         
CREATE CACHED TABLE "PUBLIC"."PRODUCT_CATEGORIES"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 49) NOT NULL,
    "NAME" CHARACTER VARYING(255) NOT NULL,
    "SLUG" CHARACTER VARYING(255) NOT NULL
);     
ALTER TABLE "PUBLIC"."PRODUCT_CATEGORIES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5" PRIMARY KEY("ID");           
-- 6 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCT_CATEGORIES;      
INSERT INTO "PUBLIC"."PRODUCT_CATEGORIES" VALUES
(3, 'Connectivity', 'connectivity'),
(4, 'Modular Wiring', 'modular-wiring'),
(27, 'SMPS', 'smps'),
(28, 'Sensors', 'sensors'),
(30, 'Encoders', 'encoders'),
(48, 'Demovideo', 'demovideo');          
CREATE CACHED TABLE "PUBLIC"."PRODUCTS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 10) NOT NULL,
    "DESCRIPTION" CHARACTER VARYING(2000),
    "IMAGE_URL" CHARACTER VARYING(255) NOT NULL,
    "NAME" CHARACTER VARYING(255) NOT NULL,
    "SHORT_DESCRIPTION" CHARACTER VARYING(500),
    "CATEGORY_ID" BIGINT NOT NULL
);         
ALTER TABLE "PUBLIC"."PRODUCTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("ID");     
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCTS;
INSERT INTO "PUBLIC"."PRODUCTS" VALUES
(6, 'Available in 5/8/16/24 Ports with/without MM/SM FO. Support auto-negotiation and auto-MDI/MDI-X. Rigid housing design. DIN-Rail and wall mounting enabled.', 'https://res.cloudinary.com/dhwvgcaii/image/upload/v1762839334/product_images/yq9lg7rzrnmbvjmtvceh.jpg', 'Unmanaged Switch', 'Available in 5/8/16/24 Ports with/without MM/SM FO. Support auto-negotiation and auto-MDI/MDI-X. Rigid housing design. DIN-Rail and wall mounting enabled.', 3),
(7, 'This is an extender wire. It is used to extend a present network wiring.', 'https://res.cloudinary.com/dhwvgcaii/image/upload/v1762839601/product_images/akfgtzacgmt67cno4v1z.jpg', 'Extender cables', 'This is an extender wire.', 4),
(8, 'This is a demonstration of function', 'https://res.cloudinary.com/dhwvgcaii/image/upload/v1762855371/product_images/ana3sytay2dlguihl4zy.jpg', 'Generic sensor', 'This is a demo', 28),
(9, 'Will do later', 'https://res.cloudinary.com/dhwvgcaii/image/upload/v1771234325/product_images/siakfeayzgprbfhkg02w.jpg', 'Demo', 'This is desc', 48);              
CREATE CACHED TABLE "PUBLIC"."USERS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 6) NOT NULL,
    "EMAIL" CHARACTER VARYING(255) NOT NULL,
    "FIRST_NAME" CHARACTER VARYING(255),
    "LAST_NAME" CHARACTER VARYING(255),
    "PASSWORD" CHARACTER VARYING(255) NOT NULL,
    "ROLE" ENUM('ROLE_ADMIN', 'ROLE_USER') NOT NULL
);     
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");        
-- 5 +/- SELECT COUNT(*) FROM PUBLIC.USERS;   
INSERT INTO "PUBLIC"."USERS" VALUES
(1, 's@gmail.com', 'Souptik', 'Sarkar', '$2a$10$4J0w/f2Rr5ce.zs3ObmSxOBJFfyzJ5DloUL9kr7cLCIbKz4QFtMUe', 'ROLE_USER'),
(2, 'admin@anyessglobal.com', 'Admin', 'User', '$2a$10$gkwFs7c2eHriW0tMXLRTc.Fr1bDTQxWBA6kDI80XctVMtLBatjA4y', 'ROLE_USER'),
(3, 'admin1@anyessglobal.com', 'Shakhya', 'Halder', '$2a$10$nAAeGyTGfkB73g1rPnZt6ORy9Mb7IOW2uA/GGugdA2S.AnzAL1ZCi', 'ROLE_USER'),
(4, 'd@gmail.com', 'Ratan', 'Desai', '$2a$10$pEewijuQSPP59Vd71Eeb8OI2wn46n5e77OjGIHQ7klapWDmocTiha', 'ROLE_USER'),
(5, 'q@gmail.com', 'Hals', 'Tals', '$2a$10$4J0w/f2Rr5ce.zs3ObmSxOBJFfyzJ5DloUL9kr7cLCIbKz4QFtMUe', 'ROLE_USER');             
ALTER TABLE "PUBLIC"."PRODUCT_CATEGORIES" ADD CONSTRAINT "PUBLIC"."UKFL075BWASJWSXYBK4X174BEFX" UNIQUE NULLS DISTINCT ("NAME");               
ALTER TABLE "PUBLIC"."PRODUCT_CATEGORIES" ADD CONSTRAINT "PUBLIC"."UK6H198AR0XRONFOXLVNQ7LSFC0" UNIQUE NULLS DISTINCT ("SLUG");               
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."UK6DOTKOTT2KJSP8VW4D0M25FB7" UNIQUE NULLS DISTINCT ("EMAIL");           
ALTER TABLE "PUBLIC"."PRODUCTS" ADD CONSTRAINT "PUBLIC"."FK6T5DTW6TYO83YWLJWOHUC6G7K" FOREIGN KEY("CATEGORY_ID") REFERENCES "PUBLIC"."PRODUCT_CATEGORIES"("ID") NOCHECK;      
